/* 과목별 문제 은행. answer는 options 배열의 0-based 인덱스입니다. */

const QUESTION_BANK = {
  korean: {
    title: '9급 국어',
    short: '국어',
    /* 문항은 Supabase questions 테이블에서 로드합니다. */
    questions: [],
  },

  english: {
    title: '9급 영어',
    short: '영어',
    questions: [
      {
        topic: '문법 · 수 일치',
        q: 'Choose the correct answer: She ___ to school every day.',
        options: ['go', 'goes', 'going', 'gone'],
        answer: 1,
        explain: '주어가 3인칭 단수(She)이고 현재 시제의 반복적 습관을 나타내므로 동사에 -es를 붙인 goes가 옳습니다.',
      },
      {
        topic: '어휘',
        q: "Choose the word closest in meaning to 'diligent'.",
        options: ['lazy', 'hardworking', 'careless', 'talkative'],
        answer: 1,
        explain: "diligent는 '부지런한, 성실한'의 뜻이므로 hardworking과 가장 가깝습니다. lazy(게으른)는 반의어입니다.",
      },
      {
        topic: '문법 · 조동사',
        q: 'Choose the grammatically correct sentence.',
        options: [
          "He don't like coffee.",
          "He doesn't likes coffee.",
          "He doesn't like coffee.",
          'He not like coffee.',
        ],
        answer: 2,
        explain: '3인칭 단수 주어의 부정문은 doesn\'t를 쓰고, 그 뒤에는 동사원형이 옵니다. 따라서 doesn\'t like가 옳습니다.',
      },
      {
        topic: '문법 · 전치사',
        q: 'I have been waiting ___ two hours.',
        options: ['since', 'for', 'during', 'while'],
        answer: 1,
        explain: "기간의 길이 앞에는 for를 씁니다. since는 시작 시점(since 2020), during은 특정 기간 명사(during the vacation) 앞에 옵니다.",
      },
      {
        topic: '어휘',
        q: "Choose the meaning of 'postpone'.",
        options: ['연기하다', '취소하다', '제출하다', '참석하다'],
        answer: 0,
        explain: "postpone은 '(예정된 일을) 뒤로 미루다, 연기하다'의 뜻으로 put off와 같은 의미입니다.",
      },
      {
        topic: '문법 · 시제',
        q: 'By the time he arrived, the movie ___.',
        options: ['started', 'has started', 'had started', 'will start'],
        answer: 2,
        explain: '과거의 어느 시점(he arrived)보다 더 이전에 완료된 일을 나타내므로 과거완료 had started가 옳습니다.',
      },
      {
        topic: '문법 · 관계사',
        q: 'This is the book ___ I bought yesterday.',
        options: ['who', 'which', 'whose', 'where'],
        answer: 1,
        explain: '선행사 the book이 사물이고 관계절에서 목적어 역할을 하므로 which(또는 that)가 옳습니다.',
      },
      {
        topic: '숙어',
        q: "Choose the meaning of the phrasal verb 'put off'.",
        options: ['미루다', '입다', '참다', '제출하다'],
        answer: 0,
        explain: "put off는 '연기하다, 미루다'의 뜻입니다. '입다'는 put on, '제출하다'는 hand in입니다.",
      },
      {
        topic: '문법 · 수동태',
        q: 'The letter ___ by John last night.',
        options: ['wrote', 'was written', 'has wrote', 'writing'],
        answer: 1,
        explain: '주어(The letter)가 동작을 받는 대상이고 시점이 과거이므로 과거 수동태 was written이 옳습니다.',
      },
      {
        topic: '어휘',
        q: "Choose the meaning of 'inevitable'.",
        options: ['피할 수 없는', '불가능한', '유용한', '사소한'],
        answer: 0,
        explain: "inevitable은 '불가피한, 피할 수 없는'의 뜻으로 unavoidable과 같은 의미입니다.",
      },
    ],
  },

  history: {
    title: '한국사',
    short: '한국사',
    questions: [
      {
        topic: '조선 전기',
        q: '훈민정음을 창제하여 반포한 왕은?',
        options: ['태종', '세종', '성종', '세조'],
        answer: 1,
        explain: '세종은 1443년 훈민정음을 창제하고 1446년에 반포하였습니다. 집현전을 중심으로 한 학문 진흥도 세종의 대표적 업적입니다.',
      },
      {
        topic: '고려',
        q: '고려를 건국한 인물은?',
        options: ['왕건', '이성계', '견훤', '궁예'],
        answer: 0,
        explain: '왕건은 918년 고려를 건국하고 936년 후삼국을 통일하였습니다. 견훤은 후백제, 궁예는 후고구려를 세웠습니다.',
      },
      {
        topic: '일제강점기',
        q: '3·1 운동이 일어난 해는?',
        options: ['1910년', '1919년', '1926년', '1945년'],
        answer: 1,
        explain: '3·1 운동은 1919년에 전국적으로 전개된 최대 규모의 독립운동으로, 그 결과 대한민국 임시정부가 수립되었습니다.',
      },
      {
        topic: '삼국 · 통일신라',
        q: '삼국 통일을 완성한 신라의 왕은?',
        options: ['진흥왕', '문무왕', '법흥왕', '지증왕'],
        answer: 1,
        explain: '문무왕은 668년 고구려를 멸망시킨 뒤 나당 전쟁에서 승리하여 676년 삼국 통일을 완성하였습니다.',
      },
      {
        topic: '조선 전기',
        q: '조선이 건국된 해는?',
        options: ['1388년', '1392년', '1400년', '1418년'],
        answer: 1,
        explain: '이성계는 1392년 조선을 건국하였습니다. 1388년은 위화도 회군이 일어난 해입니다.',
      },
      {
        topic: '조선 후기',
        q: '임진왜란이 시작된 해는?',
        options: ['1592년', '1597년', '1627년', '1636년'],
        answer: 0,
        explain: '임진왜란은 1592년에 시작되었습니다. 1597년은 정유재란, 1627년은 정묘호란, 1636년은 병자호란입니다.',
      },
      {
        topic: '근대',
        q: '갑오개혁이 추진된 해는?',
        options: ['1876년', '1894년', '1905년', '1910년'],
        answer: 1,
        explain: '갑오개혁은 1894년부터 추진된 근대적 개혁으로 신분제 폐지, 조세의 금납화 등이 이루어졌습니다.',
      },
      {
        topic: '남북국 시대',
        q: '발해를 건국한 인물은?',
        options: ['대조영', '온조', '주몽', '김수로'],
        answer: 0,
        explain: '대조영은 698년 고구려 유민과 말갈인을 이끌고 발해를 건국하였습니다.',
      },
      {
        topic: '삼국',
        q: '광개토대왕의 업적으로 옳은 것은?',
        options: [
          '훈민정음을 창제하였다.',
          '영토를 만주 지역까지 크게 확장하였다.',
          '삼국을 통일하였다.',
          '노비안검법을 실시하였다.',
        ],
        answer: 1,
        explain: '광개토대왕은 정복 활동을 통해 만주 대부분과 한반도 중부까지 영토를 넓혔습니다. 노비안검법은 고려 광종의 정책입니다.',
      },
      {
        topic: '현대',
        q: '8·15 광복이 이루어진 해는?',
        options: ['1943년', '1945년', '1948년', '1950년'],
        answer: 1,
        explain: '1945년 8월 15일 일본의 항복으로 광복을 맞았습니다. 1948년은 대한민국 정부 수립, 1950년은 6·25 전쟁 발발 연도입니다.',
      },
    ],
  },

  adminlaw: {
    title: '행정법',
    short: '행정법',
    questions: [
      {
        topic: '행정의 실효성 확보',
        q: '다음 중 행정상 강제집행 수단에 해당하지 않는 것은?',
        options: ['대집행', '이행강제금', '직접강제', '행정벌'],
        answer: 3,
        explain: '행정상 강제집행에는 대집행, 이행강제금, 직접강제, 강제징수가 있습니다. 행정벌은 과거의 의무 위반에 대한 제재이므로 강제집행 수단이 아닙니다.',
      },
      {
        topic: '행정소송',
        q: '취소소송은 처분이 있음을 안 날부터 며칠 이내에 제기해야 하는가?',
        options: ['30일', '60일', '90일', '1년'],
        answer: 2,
        explain: '행정소송법상 취소소송은 처분이 있음을 안 날부터 90일, 처분이 있은 날부터 1년 이내에 제기해야 합니다.',
      },
      {
        topic: '행정심판',
        q: '행정심판은 처분이 있음을 알게 된 날부터 며칠 이내에 청구해야 하는가?',
        options: ['30일', '60일', '90일', '180일'],
        answer: 2,
        explain: '행정심판법상 취소심판은 처분이 있음을 알게 된 날부터 90일, 처분이 있었던 날부터 180일 이내에 청구해야 합니다.',
      },
      {
        topic: '행정행위',
        q: '다음 중 준법률행위적 행정행위에 해당하는 것은?',
        options: ['허가', '인가', '확인', '특허'],
        answer: 2,
        explain: '준법률행위적 행정행위에는 확인, 공증, 통지, 수리가 있습니다. 허가·인가·특허는 법률행위적 행정행위 중 형성적·명령적 행위에 해당합니다.',
      },
      {
        topic: '행정법의 원칙',
        q: '법률의 근거 없이 국민의 권리를 제한할 수 없다는 원칙은?',
        options: ['신뢰보호의 원칙', '법률유보의 원칙', '비례의 원칙', '평등의 원칙'],
        answer: 1,
        explain: '법률유보의 원칙은 국민의 권리 제한이나 의무 부과에는 반드시 법률의 근거가 있어야 한다는 원칙입니다.',
      },
      {
        topic: '행정법의 원칙',
        q: '비례의 원칙의 내용에 해당하지 않는 것은?',
        options: ['목적의 정당성', '수단의 적합성', '침해의 최소성', '신뢰의 보호'],
        answer: 3,
        explain: '비례의 원칙은 목적의 정당성, 수단의 적합성, 침해의 최소성, 법익의 균형성으로 구성됩니다. 신뢰의 보호는 별개의 신뢰보호 원칙입니다.',
      },
      {
        topic: '행정지도',
        q: '행정지도의 법적 성질은?',
        options: ['권력적 사실행위', '비권력적 사실행위', '행정행위', '행정입법'],
        answer: 1,
        explain: '행정지도는 상대방의 임의적 협력을 전제로 하는 비권력적 사실행위로, 원칙적으로 법적 구속력이 없습니다.',
      },
      {
        topic: '국가배상',
        q: '국가배상법상 공무원의 위법한 직무행위로 인한 배상책임의 요건이 아닌 것은?',
        options: ['직무를 집행하면서 한 행위', '고의 또는 과실', '법령 위반', '손해 발생의 예견 가능성'],
        answer: 3,
        explain: '국가배상책임의 요건은 공무원의 직무행위, 고의 또는 과실, 법령 위반(위법성), 손해의 발생 및 인과관계입니다. 예견 가능성은 독립된 요건이 아닙니다.',
      },
      {
        topic: '행정입법',
        q: '다음 중 법규명령에 해당하지 않는 것은?',
        options: ['대통령령', '총리령', '부령', '행정규칙'],
        answer: 3,
        explain: '법규명령은 대통령령·총리령·부령과 같이 대외적 구속력을 가지는 규범입니다. 행정규칙은 원칙적으로 행정조직 내부에서만 효력을 가집니다.',
      },
      {
        topic: '행정행위의 하자',
        q: '무효인 행정행위와 취소할 수 있는 행정행위를 구별하는 통설·판례의 기준은?',
        options: ['중대명백설', '명백성 보충요건설', '조사의무설', '구체적 가치형량설'],
        answer: 0,
        explain: '통설과 판례는 하자가 중대하고 동시에 명백한 경우에만 무효로 보는 중대명백설을 취하고 있습니다.',
      },
    ],
  },

  adminsci: {
    title: '행정학',
    short: '행정학',
    questions: [
      {
        topic: '조직론',
        q: '베버(M. Weber)가 제시한 이상적 관료제의 특징이 아닌 것은?',
        options: ['계층제적 구조', '분업과 전문화', '문서에 의한 행정', '정실에 따른 임용'],
        answer: 3,
        explain: '베버의 관료제는 계층제, 분업과 전문화, 문서주의, 법규에 의한 지배, 실적에 따른 임용을 특징으로 합니다. 정실 임용은 관료제 이전의 엽관주의적 요소입니다.',
      },
      {
        topic: '행정학의 기초',
        q: "행정 관리 기능을 'POSDCORB'로 제시한 학자는?",
        options: ['귤릭(Gulick)', '베버(Weber)', '사이먼(Simon)', '윌슨(Wilson)'],
        answer: 0,
        explain: '귤릭은 기획·조직·인사·지휘·조정·보고·예산의 머리글자를 딴 POSDCORB로 최고관리자의 기능을 제시하였습니다.',
      },
      {
        topic: '행정이론',
        q: '신공공관리론(NPM)의 특징으로 가장 적절한 것은?',
        options: ['성과와 결과 중심의 관리', '절차와 규정의 강화', '정부 독점의 확대', '계층제적 통제의 강화'],
        answer: 0,
        explain: '신공공관리론은 시장 원리와 민간 경영 기법을 도입하여 성과·결과 중심의 관리, 고객 지향, 경쟁 도입을 강조합니다.',
      },
      {
        topic: '정책론',
        q: '정책이 집행되는 과정과 활동을 대상으로 하는 평가는?',
        options: ['총괄평가', '과정평가', '사전평가', '메타평가'],
        answer: 1,
        explain: '과정평가는 정책 집행 과정의 활동과 절차를 평가합니다. 총괄평가는 정책의 효과와 성과를 사후에 평가하는 것입니다.',
      },
      {
        topic: '재무행정',
        q: "'모든 수입과 지출을 예산에 계상해야 한다'는 예산 원칙은?",
        options: ['통일성의 원칙', '완전성의 원칙', '한정성의 원칙', '단일성의 원칙'],
        answer: 1,
        explain: '완전성의 원칙(총계주의)은 모든 수입과 지출을 예산에 빠짐없이 계상해야 한다는 원칙입니다. 통일성은 특정 수입을 특정 지출에 연계하지 않는 원칙입니다.',
      },
      {
        topic: '인사행정',
        q: '위생요인과 동기요인을 구분하여 동기부여를 설명한 학자는?',
        options: ['매슬로(Maslow)', '허즈버그(Herzberg)', '맥그리거(McGregor)', '앨더퍼(Alderfer)'],
        answer: 1,
        explain: '허즈버그의 2요인 이론은 불만족을 줄이는 위생요인과 만족을 높이는 동기요인을 구분하였습니다.',
      },
      {
        topic: '인사행정',
        q: '매슬로의 욕구 5단계 중 가장 상위의 욕구는?',
        options: ['생리적 욕구', '안전의 욕구', '존경의 욕구', '자아실현의 욕구'],
        answer: 3,
        explain: '매슬로는 생리적 → 안전 → 사회적(애정·소속) → 존경 → 자아실현의 순서로 욕구가 계층을 이룬다고 보았습니다.',
      },
      {
        topic: '재무행정',
        q: '우리나라의 예산 회계연도는?',
        options: ['1월 1일 ~ 12월 31일', '3월 1일 ~ 2월 말일', '4월 1일 ~ 3월 31일', '7월 1일 ~ 6월 30일'],
        answer: 0,
        explain: '우리나라의 회계연도는 매년 1월 1일에 시작하여 12월 31일에 종료됩니다.',
      },
      {
        topic: '행정통제',
        q: '다음 중 행정에 대한 내부통제에 해당하는 것은?',
        options: ['국회의 국정감사', '감사원의 직무감찰', '법원의 행정재판', '시민단체의 감시'],
        answer: 1,
        explain: '감사원은 대통령 소속의 행정부 내 기관이므로 그 직무감찰은 내부통제에 해당합니다. 국회·법원·시민단체에 의한 통제는 외부통제입니다.',
      },
      {
        topic: '정책론',
        q: '제한된 합리성을 전제로 만족모형을 제시한 학자는?',
        options: ['사이먼(Simon)', '린드블롬(Lindblom)', '에치오니(Etzioni)', '앨리슨(Allison)'],
        answer: 0,
        explain: '사이먼은 인간의 인지 능력에 한계가 있다는 제한된 합리성을 근거로, 최적해가 아니라 만족할 만한 대안을 선택한다는 만족모형을 제시하였습니다.',
      },
    ],
  },

  peducation: {
    title: '교육학개론',
    short: '교육학',
    questions: [],
  },

  localtax: {
    title: '지방세법',
    short: '지방세법',
    questions: [],
  },

  accounting: {
    title: '회계학',
    short: '회계학',
    questions: [],
  },

  socialwelfare: {
    title: '사회복지학개론',
    short: '사회복지',
    questions: [],
  },
};
