-- 오답 집계 테이블. 이미 있으면 정책·유니크만 맞춥니다.
create table if not exists public.wrong_answers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  wrong_count integer not null default 1,
  mastered boolean not null default false,
  last_wrong_at timestamptz not null default now()
);

create unique index if not exists wrong_answers_user_question_uidx
  on public.wrong_answers (user_id, question_id);

alter table public.wrong_answers enable row level security;

revoke all on table public.wrong_answers from anon, public;
grant select, insert, update, delete on table public.wrong_answers to authenticated;

drop policy if exists wrong_answers_select_own on public.wrong_answers;
drop policy if exists wrong_answers_insert_own on public.wrong_answers;
drop policy if exists wrong_answers_update_own on public.wrong_answers;
drop policy if exists wrong_answers_delete_own on public.wrong_answers;

create policy wrong_answers_select_own on public.wrong_answers
  for select to authenticated using (auth.uid() = user_id);
create policy wrong_answers_insert_own on public.wrong_answers
  for insert to authenticated with check (auth.uid() = user_id);
create policy wrong_answers_update_own on public.wrong_answers
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy wrong_answers_delete_own on public.wrong_answers
  for delete to authenticated using (auth.uid() = user_id);

notify pgrst, 'reload schema';
