-- 오답노트. Supabase SQL Editor에서 이 파일 전체를 실행하세요.
-- 기존 public.wrong_notes 가 있어도 컬럼·RPC·정책만 맞춥니다.

create table if not exists public.wrong_notes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  question_id bigint references public.questions(id) on delete set null,
  subjects text,
  question_index integer,
  topic text,
  note text,
  selected_answer integer,
  wrong_count integer not null default 1,
  last_wrong_at timestamptz not null default now()
);

alter table public.wrong_notes add column if not exists subjects text;
alter table public.wrong_notes add column if not exists question_index integer;
alter table public.wrong_notes add column if not exists topic text;
alter table public.wrong_notes add column if not exists note text;
alter table public.wrong_notes add column if not exists selected_answer integer;
alter table public.wrong_notes add column if not exists wrong_count integer;
alter table public.wrong_notes add column if not exists last_wrong_at timestamptz;

alter table public.wrong_notes alter column user_id drop not null;
alter table public.wrong_notes alter column question_id drop not null;
alter table public.wrong_notes alter column wrong_count set default 1;
alter table public.wrong_notes alter column last_wrong_at set default now();

do $$
declare
  rec record;
begin
  for rec in
    select c.conname
    from pg_constraint c
    join pg_class t on c.conrelid = t.oid
    join pg_namespace n on n.oid = t.relnamespace
    join unnest(c.conkey) as k(attnum) on true
    join pg_attribute a on a.attrelid = t.oid and a.attnum = k.attnum
    where n.nspname = 'public'
      and t.relname = 'wrong_notes'
      and c.contype = 'f'
      and a.attname = 'question_id'
  loop
    execute format('alter table public.wrong_notes drop constraint if exists %I', rec.conname);
  end loop;
end $$;

alter table public.wrong_notes
  add constraint wrong_notes_question_id_fkey
  foreign key (question_id) references public.questions(id) on delete set null;

create unique index if not exists wrong_notes_owner_question_uidx
  on public.wrong_notes (
    coalesce(user_id, '00000000-0000-0000-0000-000000000000'::uuid),
    question_id
  )
  where question_id is not null;

create unique index if not exists wrong_notes_owner_index_uidx
  on public.wrong_notes (
    coalesce(user_id, '00000000-0000-0000-0000-000000000000'::uuid),
    subjects,
    question_index
  )
  where subjects is not null and question_index is not null;

create index if not exists wrong_notes_user_last_idx
  on public.wrong_notes (user_id, last_wrong_at desc);

alter table public.wrong_notes enable row level security;

revoke all on table public.wrong_notes from anon, public;
grant select, insert, update, delete on table public.wrong_notes to authenticated;

drop policy if exists wrong_notes_select_own on public.wrong_notes;
drop policy if exists wrong_notes_insert_own on public.wrong_notes;
drop policy if exists wrong_notes_update_own on public.wrong_notes;
drop policy if exists wrong_notes_delete_own on public.wrong_notes;

create policy wrong_notes_select_own on public.wrong_notes
  for select to authenticated using (auth.uid() = user_id);
create policy wrong_notes_insert_own on public.wrong_notes
  for insert to authenticated with check (auth.uid() = user_id);
create policy wrong_notes_update_own on public.wrong_notes
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy wrong_notes_delete_own on public.wrong_notes
  for delete to authenticated using (auth.uid() = user_id);

drop function if exists public.list_wrong_notes();
drop function if exists public.upsert_wrong_note(bigint, text, integer, text, text, integer, timestamptz, boolean);
drop function if exists public.delete_wrong_note(bigint, text, integer, boolean);
drop function if exists public.claim_guest_wrong_notes();
drop function if exists public.wrong_notes_owner();

create or replace function public.wrong_notes_owner()
returns uuid
language sql
stable
as $$
  select auth.uid();
$$;

create or replace function public.list_wrong_notes()
returns setof public.wrong_notes
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is not null then
    return query
      select *
      from public.wrong_notes
      where user_id = v_uid
      order by last_wrong_at desc;
  else
    return query
      select *
      from public.wrong_notes
      where user_id is null
      order by last_wrong_at desc;
  end if;
end;
$$;

create or replace function public.upsert_wrong_note(
  p_question_id bigint default null,
  p_subjects text default null,
  p_question_index integer default null,
  p_topic text default null,
  p_note text default null,
  p_selected_answer integer default null,
  p_last_wrong_at timestamptz default null,
  p_increment boolean default true
)
returns public.wrong_notes
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_row public.wrong_notes;
  v_at timestamptz := coalesce(p_last_wrong_at, now());
begin
  if p_question_id is not null then
    select * into v_row
    from public.wrong_notes
    where question_id = p_question_id
      and ((v_uid is null and user_id is null) or user_id = v_uid)
    order by last_wrong_at desc
    limit 1;
  end if;

  if v_row.id is null and p_subjects is not null and p_question_index is not null then
    select * into v_row
    from public.wrong_notes
    where subjects = p_subjects
      and question_index = p_question_index
      and ((v_uid is null and user_id is null) or user_id = v_uid)
    order by last_wrong_at desc
    limit 1;
  end if;

  if v_row.id is not null then
    update public.wrong_notes
    set
      question_id = coalesce(p_question_id, v_row.question_id),
      subjects = coalesce(p_subjects, v_row.subjects),
      question_index = coalesce(p_question_index, v_row.question_index),
      topic = coalesce(p_topic, v_row.topic),
      note = coalesce(p_note, v_row.note),
      selected_answer = coalesce(p_selected_answer, v_row.selected_answer),
      wrong_count = case
        when p_increment then coalesce(v_row.wrong_count, 1) + 1
        else greatest(coalesce(v_row.wrong_count, 1), 1)
      end,
      last_wrong_at = v_at
    where id = v_row.id
    returning * into v_row;
    return v_row;
  end if;

  insert into public.wrong_notes (
    user_id,
    question_id,
    subjects,
    question_index,
    topic,
    note,
    selected_answer,
    wrong_count,
    last_wrong_at
  ) values (
    v_uid,
    p_question_id,
    p_subjects,
    p_question_index,
    p_topic,
    p_note,
    p_selected_answer,
    1,
    v_at
  )
  returning * into v_row;

  return v_row;
end;
$$;

create or replace function public.delete_wrong_note(
  p_question_id bigint default null,
  p_subjects text default null,
  p_question_index integer default null,
  p_all boolean default false
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_count integer := 0;
begin
  if p_all then
    delete from public.wrong_notes
    where (v_uid is null and user_id is null) or user_id = v_uid;
    get diagnostics v_count = row_count;
    return v_count;
  end if;

  if p_question_id is not null then
    delete from public.wrong_notes
    where question_id = p_question_id
      and ((v_uid is null and user_id is null) or user_id = v_uid);
    get diagnostics v_count = row_count;
  end if;

  if v_count = 0 and p_subjects is not null and p_question_index is not null then
    delete from public.wrong_notes
    where subjects = p_subjects
      and question_index = p_question_index
      and ((v_uid is null and user_id is null) or user_id = v_uid);
    get diagnostics v_count = row_count;
  end if;

  return v_count;
end;
$$;

create or replace function public.claim_guest_wrong_notes()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_count integer := 0;
  rec record;
begin
  if v_uid is null then
    return 0;
  end if;

  for rec in
    select *
    from public.wrong_notes
    where user_id is null
  loop
    if exists (
      select 1
      from public.wrong_notes
      where user_id = v_uid
        and (
          (rec.question_id is not null and question_id = rec.question_id)
          or (
            rec.subjects is not null
            and rec.question_index is not null
            and subjects = rec.subjects
            and question_index = rec.question_index
          )
        )
    ) then
      delete from public.wrong_notes where id = rec.id;
    else
      update public.wrong_notes set user_id = v_uid where id = rec.id;
      v_count := v_count + 1;
    end if;
  end loop;

  return v_count;
end;
$$;

grant execute on function public.list_wrong_notes() to anon, authenticated;
grant execute on function public.upsert_wrong_note(bigint, text, integer, text, text, integer, timestamptz, boolean) to anon, authenticated;
grant execute on function public.delete_wrong_note(bigint, text, integer, boolean) to anon, authenticated;
grant execute on function public.claim_guest_wrong_notes() to authenticated;
grant execute on function public.wrong_notes_owner() to anon, authenticated;

notify pgrst, 'reload schema';
