-- 나의 성적(과목 · 전체 문제 · 정답 · 정답률 · 난이도).
-- Supabase SQL Editor에서 이 파일 전체를 실행하세요.

create table if not exists public.subject_grades (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  subjects text not null,
  title text,
  total integer not null default 0,
  attempted integer not null default 0,
  correct integer not null default 0,
  rate integer not null default 0,
  difficulty text not null default 'empty',
  updated_at timestamptz not null default now()
);

alter table public.subject_grades add column if not exists subjects text;
alter table public.subject_grades add column if not exists title text;
alter table public.subject_grades add column if not exists total integer;
alter table public.subject_grades add column if not exists attempted integer;
alter table public.subject_grades add column if not exists correct integer;
alter table public.subject_grades add column if not exists rate integer;
alter table public.subject_grades add column if not exists difficulty text;
alter table public.subject_grades add column if not exists updated_at timestamptz;

alter table public.subject_grades alter column user_id drop not null;
alter table public.subject_grades alter column total set default 0;
alter table public.subject_grades alter column attempted set default 0;
alter table public.subject_grades alter column correct set default 0;
alter table public.subject_grades alter column rate set default 0;
alter table public.subject_grades alter column difficulty set default 'empty';
alter table public.subject_grades alter column updated_at set default now();

create unique index if not exists subject_grades_owner_subject_uidx
  on public.subject_grades (
    coalesce(user_id, '00000000-0000-0000-0000-000000000000'::uuid),
    subjects
  );

alter table public.subject_grades enable row level security;

revoke all on table public.subject_grades from anon, public;
grant select, insert, update, delete on table public.subject_grades to authenticated;

drop policy if exists subject_grades_select_own on public.subject_grades;
drop policy if exists subject_grades_insert_own on public.subject_grades;
drop policy if exists subject_grades_update_own on public.subject_grades;
drop policy if exists subject_grades_delete_own on public.subject_grades;

create policy subject_grades_select_own on public.subject_grades
  for select to authenticated using (auth.uid() = user_id);
create policy subject_grades_insert_own on public.subject_grades
  for insert to authenticated with check (auth.uid() = user_id);
create policy subject_grades_update_own on public.subject_grades
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy subject_grades_delete_own on public.subject_grades
  for delete to authenticated using (auth.uid() = user_id);

drop function if exists public.list_subject_grades();
drop function if exists public.save_subject_grades(jsonb);
drop function if exists public.claim_guest_subject_grades();

create or replace function public.list_subject_grades()
returns setof public.subject_grades
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is not null then
    return query
      select *
      from public.subject_grades
      where user_id = v_uid
      order by id;
  else
    return query
      select *
      from public.subject_grades
      where user_id is null
      order by id;
  end if;
end;
$$;

create or replace function public.save_subject_grades(p_rows jsonb)
returns setof public.subject_grades
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  rec jsonb;
  v_subjects text;
  v_title text;
  v_total integer;
  v_attempted integer;
  v_correct integer;
  v_rate integer;
  v_difficulty text;
begin
  delete from public.subject_grades
  where (v_uid is null and user_id is null) or user_id = v_uid;

  for rec in
    select value from jsonb_array_elements(coalesce(p_rows, '[]'::jsonb))
  loop
    v_subjects := nullif(trim(both from coalesce(rec->>'subjects', rec->>'id', '')), '');
    if v_subjects is null then
      continue;
    end if;
    v_title := nullif(trim(both from coalesce(rec->>'title', '')), '');
    v_total := greatest(coalesce((rec->>'total')::integer, 0), 0);
    v_attempted := greatest(coalesce((rec->>'attempted')::integer, 0), 0);
    v_correct := greatest(coalesce((rec->>'correct')::integer, 0), 0);
    v_rate := greatest(coalesce((rec->>'rate')::integer, (rec->>'totalRate')::integer, 0), 0);
    v_difficulty := coalesce(nullif(trim(both from rec->>'difficulty'), ''), 'empty');
    if v_difficulty not in ('high', 'mid', 'low', 'empty') then
      v_difficulty := 'empty';
    end if;

    insert into public.subject_grades (
      user_id, subjects, title, total, attempted, correct, rate, difficulty, updated_at
    ) values (
      v_uid, v_subjects, v_title, v_total, v_attempted, v_correct, v_rate, v_difficulty, now()
    );
  end loop;

  return query
    select *
    from public.subject_grades
    where (v_uid is null and user_id is null) or user_id = v_uid
    order by id;
end;
$$;

create or replace function public.claim_guest_subject_grades()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_own integer := 0;
  v_guest integer := 0;
begin
  if v_uid is null then
    return 0;
  end if;

  select count(*) into v_own from public.subject_grades where user_id = v_uid;
  select count(*) into v_guest from public.subject_grades where user_id is null;

  if v_guest = 0 then
    return 0;
  end if;

  if v_own > 0 then
    delete from public.subject_grades where user_id is null;
    return 0;
  end if;

  update public.subject_grades
  set user_id = v_uid, updated_at = now()
  where user_id is null;
  return v_guest;
end;
$$;

grant execute on function public.list_subject_grades() to anon, authenticated;
grant execute on function public.save_subject_grades(jsonb) to anon, authenticated;
grant execute on function public.claim_guest_subject_grades() to authenticated;

notify pgrst, 'reload schema';
