-- 학습 현황(총 문제 풀이 · 정답률 · 학습일 수 · 연속 학습).
-- Supabase SQL Editor에서 이 파일 전체를 실행하세요.

create table if not exists public.study_stats (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  attempted integer not null default 0,
  correct integer not null default 0,
  rate integer not null default 0,
  study_days integer not null default 0,
  streak integer not null default 0,
  last_study_on date,
  study_dates date[] not null default '{}',
  updated_at timestamptz not null default now()
);

alter table public.study_stats add column if not exists attempted integer;
alter table public.study_stats add column if not exists correct integer;
alter table public.study_stats add column if not exists rate integer;
alter table public.study_stats add column if not exists study_days integer;
alter table public.study_stats add column if not exists streak integer;
alter table public.study_stats add column if not exists last_study_on date;
alter table public.study_stats add column if not exists study_dates date[];
alter table public.study_stats add column if not exists updated_at timestamptz;

alter table public.study_stats alter column user_id drop not null;
alter table public.study_stats alter column attempted set default 0;
alter table public.study_stats alter column correct set default 0;
alter table public.study_stats alter column rate set default 0;
alter table public.study_stats alter column study_days set default 0;
alter table public.study_stats alter column streak set default 0;
alter table public.study_stats alter column study_dates set default '{}';
alter table public.study_stats alter column updated_at set default now();

create unique index if not exists study_stats_owner_uidx
  on public.study_stats (coalesce(user_id, '00000000-0000-0000-0000-000000000000'::uuid));

alter table public.study_stats enable row level security;

revoke all on table public.study_stats from anon, public;
grant select, insert, update, delete on table public.study_stats to authenticated;

drop policy if exists study_stats_select_own on public.study_stats;
drop policy if exists study_stats_insert_own on public.study_stats;
drop policy if exists study_stats_update_own on public.study_stats;
drop policy if exists study_stats_delete_own on public.study_stats;

create policy study_stats_select_own on public.study_stats
  for select to authenticated using (auth.uid() = user_id);
create policy study_stats_insert_own on public.study_stats
  for insert to authenticated with check (auth.uid() = user_id);
create policy study_stats_update_own on public.study_stats
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy study_stats_delete_own on public.study_stats
  for delete to authenticated using (auth.uid() = user_id);

drop function if exists public.get_study_stats();
drop function if exists public.save_study_stats(integer, integer, integer, integer, date[]);
drop function if exists public.claim_guest_study_stats();

create or replace function public.get_study_stats()
returns setof public.study_stats
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is not null then
    return query
      select *
      from public.study_stats
      where user_id = v_uid
      limit 1;
  else
    return query
      select *
      from public.study_stats
      where user_id is null
      limit 1;
  end if;
end;
$$;

create or replace function public.save_study_stats(
  p_attempted integer default 0,
  p_correct integer default 0,
  p_study_days integer default 0,
  p_streak integer default 0,
  p_study_dates date[] default '{}'
)
returns public.study_stats
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_row public.study_stats;
  v_attempted integer := greatest(coalesce(p_attempted, 0), 0);
  v_correct integer := greatest(coalesce(p_correct, 0), 0);
  v_days integer := greatest(coalesce(p_study_days, 0), 0);
  v_streak integer := greatest(coalesce(p_streak, 0), 0);
  v_dates date[] := coalesce(p_study_dates, '{}');
  v_rate integer := 0;
  v_last date := null;
begin
  if v_attempted > 0 then
    v_rate := round((v_correct::numeric / v_attempted) * 100);
  end if;
  if array_length(v_dates, 1) is not null then
    select max(d) into v_last from unnest(v_dates) as d;
  end if;

  select * into v_row
  from public.study_stats
  where (v_uid is null and user_id is null) or user_id = v_uid
  limit 1;

  if v_row.id is not null then
    update public.study_stats
    set
      attempted = v_attempted,
      correct = v_correct,
      rate = v_rate,
      study_days = v_days,
      streak = v_streak,
      last_study_on = v_last,
      study_dates = v_dates,
      updated_at = now()
    where id = v_row.id
    returning * into v_row;
    return v_row;
  end if;

  insert into public.study_stats (
    user_id,
    attempted,
    correct,
    rate,
    study_days,
    streak,
    last_study_on,
    study_dates,
    updated_at
  ) values (
    v_uid,
    v_attempted,
    v_correct,
    v_rate,
    v_days,
    v_streak,
    v_last,
    v_dates,
    now()
  )
  returning * into v_row;

  return v_row;
end;
$$;

create or replace function public.claim_guest_study_stats()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_guest public.study_stats;
  v_own public.study_stats;
begin
  if v_uid is null then
    return 0;
  end if;

  select * into v_guest from public.study_stats where user_id is null limit 1;
  if v_guest.id is null then
    return 0;
  end if;

  select * into v_own from public.study_stats where user_id = v_uid limit 1;
  if v_own.id is not null then
    delete from public.study_stats where id = v_guest.id;
    return 0;
  end if;

  update public.study_stats set user_id = v_uid, updated_at = now() where id = v_guest.id;
  return 1;
end;
$$;

grant execute on function public.get_study_stats() to anon, authenticated;
grant execute on function public.save_study_stats(integer, integer, integer, integer, date[]) to anon, authenticated;
grant execute on function public.claim_guest_study_stats() to authenticated;

notify pgrst, 'reload schema';
