-- 회원가입 · 로그인을 Supabase Auth(auth.users)에 저장합니다.
-- Supabase 대시보드 → SQL Editor 에서 이 파일 전체를 실행하세요.
--
-- 같이 확인할 설정:
-- Authentication → Providers → Email → Confirm email 을 꺼 주세요.
-- (켜져 있으면 가입 직후 세션이 만들어지지 않습니다.)

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text,
  email text,
  target_exam text,
  target_date date,
  plan text default 'free',
  subjects text[] default '{}',
  daily_target integer default 30,
  notify jsonb default '{"study":true,"review":true,"event":false}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists subjects text[] default '{}';
alter table public.profiles add column if not exists daily_target integer default 30;
alter table public.profiles add column if not exists notify jsonb default '{"study":true,"review":true,"event":false}'::jsonb;
alter table public.profiles add column if not exists updated_at timestamptz default now();

create table if not exists public.user_answers (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  question_id bigint references public.questions(id) on delete cascade,
  selected_answer integer,
  is_correct boolean,
  response_time integer,
  answered_at timestamptz default now()
);

do $$
declare
  r record;
begin
  for r in
    select con.conname, rel.relname
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
    where nsp.nspname = 'public'
      and con.contype = 'f'
      and rel.relname in ('profiles', 'user_answers')
  loop
    if r.relname = 'profiles' and r.conname like '%id%' then
      execute format('alter table public.profiles drop constraint if exists %I', r.conname);
    elsif r.relname = 'user_answers' and r.conname like '%user_id%' then
      execute format('alter table public.user_answers drop constraint if exists %I', r.conname);
    end if;
  end loop;
end $$;

delete from public.user_answers
where user_id is not null
  and not exists (select 1 from auth.users u where u.id = user_answers.user_id);

delete from public.profiles
where not exists (select 1 from auth.users u where u.id = profiles.id);

alter table public.profiles drop constraint if exists profiles_id_fkey;
alter table public.profiles
  add constraint profiles_id_fkey
  foreign key (id) references auth.users(id) on delete cascade;

alter table public.user_answers drop constraint if exists user_answers_user_id_fkey;
alter table public.user_answers
  add constraint user_answers_user_id_fkey
  foreign key (user_id) references auth.users(id) on delete cascade;

create index if not exists user_answers_user_id_idx
  on public.user_answers (user_id, answered_at desc);

create index if not exists user_answers_question_id_idx
  on public.user_answers (question_id);

alter table public.profiles enable row level security;
alter table public.user_answers enable row level security;

revoke all on table public.profiles from anon, public;
revoke all on table public.user_answers from anon, public;

grant select, insert, update, delete on table public.profiles to authenticated;
grant select, insert, delete on table public.user_answers to authenticated;

drop policy if exists profiles_select_own on public.profiles;
drop policy if exists profiles_insert_own on public.profiles;
drop policy if exists profiles_update_own on public.profiles;
drop policy if exists profiles_delete_own on public.profiles;
drop policy if exists user_answers_select_own on public.user_answers;
drop policy if exists user_answers_insert_own on public.user_answers;
drop policy if exists user_answers_delete_own on public.user_answers;

create policy profiles_select_own on public.profiles
  for select to authenticated using (auth.uid() = id);
create policy profiles_insert_own on public.profiles
  for insert to authenticated with check (auth.uid() = id);
create policy profiles_update_own on public.profiles
  for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy profiles_delete_own on public.profiles
  for delete to authenticated using (auth.uid() = id);

create policy user_answers_select_own on public.user_answers
  for select to authenticated using (auth.uid() = user_id);
create policy user_answers_insert_own on public.user_answers
  for insert to authenticated with check (auth.uid() = user_id);
create policy user_answers_delete_own on public.user_answers
  for delete to authenticated using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, nickname, email, plan)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data->>'name',
      new.raw_user_meta_data->>'nickname',
      split_part(new.email, '@', 1)
    ),
    new.email,
    'free'
  )
  on conflict (id) do nothing;
  return new;
exception when others then
  raise warning 'handle_new_user: %', sqlerrm;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

notify pgrst, 'reload schema';
