-- 레거시 앱 회원 테이블(public.app_users).
-- 이메일 회원가입·로그인은 이제 Supabase Auth(auth.users)를 씁니다.
-- 새 프로젝트는 supabase-auth-users.sql 을 실행하세요.
-- Supabase 대시보드 → SQL Editor 에서 이 파일 전체를 실행하세요.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.app_users (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null unique,
  password_hash text,
  provider text not null default 'email',
  provider_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz,
  constraint app_users_name_len check (char_length(trim(name)) between 1 and 40),
  constraint app_users_email_fmt check (position('@' in email) > 1)
);

create unique index if not exists app_users_provider_id_uidx
  on public.app_users (provider, provider_id)
  where provider_id is not null;

create table if not exists public.app_sessions (
  id text primary key,
  user_id uuid not null references public.app_users(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists app_sessions_user_id_idx on public.app_sessions (user_id);
create index if not exists app_sessions_expires_at_idx on public.app_sessions (expires_at);

create table if not exists public.app_auth_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.app_users(id) on delete cascade,
  event text not null,
  provider text,
  created_at timestamptz not null default now()
);

create index if not exists app_auth_events_user_id_idx on public.app_auth_events (user_id, created_at desc);

alter table public.app_users enable row level security;
alter table public.app_sessions enable row level security;
alter table public.app_auth_events enable row level security;

revoke all on table public.app_users from anon, authenticated, public;
revoke all on table public.app_sessions from anon, authenticated, public;
revoke all on table public.app_auth_events from anon, authenticated, public;

create or replace function public.app_user_public(u public.app_users)
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'id', u.id,
    'name', u.name,
    'email', u.email,
    'provider', u.provider,
    'created_at', u.created_at,
    'last_login_at', u.last_login_at
  );
$$;

create or replace function public.signup_app_user(p_name text, p_email text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user public.app_users;
begin
  p_name := trim(both from coalesce(p_name, ''));
  p_email := lower(trim(both from coalesce(p_email, '')));

  if p_name = '' or position('@' in p_email) = 0 or char_length(coalesce(p_password, '')) < 6 then
    raise exception '이름·이메일·비밀번호(6자 이상)를 확인해 주세요.';
  end if;

  if exists (select 1 from public.app_users where email = p_email) then
    raise exception '이미 가입된 이메일입니다.';
  end if;

  insert into public.app_users (name, email, password_hash, provider)
  values (p_name, p_email, crypt(p_password, gen_salt('bf')), 'email')
  returning * into v_user;

  insert into public.app_auth_events (user_id, event, provider)
  values (v_user.id, 'signup', 'email');

  return public.app_user_public(v_user);
end;
$$;

create or replace function public.login_app_user(p_email text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user public.app_users;
begin
  p_email := lower(trim(both from coalesce(p_email, '')));

  select * into v_user
  from public.app_users
  where email = p_email;

  if v_user.id is null
     or v_user.password_hash is null
     or v_user.password_hash <> crypt(p_password, v_user.password_hash) then
    raise exception '이메일 또는 비밀번호가 올바르지 않습니다.';
  end if;

  update public.app_users
  set last_login_at = now(), updated_at = now()
  where id = v_user.id
  returning * into v_user;

  insert into public.app_auth_events (user_id, event, provider)
  values (v_user.id, 'login', 'email');

  return public.app_user_public(v_user);
end;
$$;

create or replace function public.upsert_social_app_user(
  p_provider text,
  p_provider_id text,
  p_name text,
  p_email text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user public.app_users;
  v_email text;
  v_name text;
  v_new boolean := false;
begin
  p_provider := lower(trim(both from coalesce(p_provider, '')));
  p_provider_id := trim(both from coalesce(p_provider_id, ''));
  v_name := trim(both from coalesce(p_name, ''));
  v_email := lower(trim(both from coalesce(p_email, '')));

  if p_provider = '' or p_provider_id = '' then
    raise exception '소셜 로그인 정보가 올바르지 않습니다.';
  end if;

  if v_name = '' then
    v_name := case when p_provider = 'kakao' then '카카오 사용자' else '네이버 사용자' end;
  end if;

  if v_email = '' or position('@' in v_email) = 0 then
    v_email := p_provider || '_' || p_provider_id || '@' || p_provider || '.passcoach.local';
  end if;

  select * into v_user
  from public.app_users
  where provider = p_provider and provider_id = p_provider_id;

  if v_user.id is null and position('@' in v_email) > 1 then
    select * into v_user
    from public.app_users
    where email = v_email;
  end if;

  if v_user.id is null then
    insert into public.app_users (name, email, provider, provider_id, last_login_at)
    values (v_name, v_email, p_provider, p_provider_id, now())
    returning * into v_user;
    v_new := true;
  else
    update public.app_users
    set
      name = coalesce(nullif(v_name, ''), name),
      provider = p_provider,
      provider_id = p_provider_id,
      email = case when position('@' in v_email) > 1 then v_email else email end,
      last_login_at = now(),
      updated_at = now()
    where id = v_user.id
    returning * into v_user;
  end if;

  insert into public.app_auth_events (user_id, event, provider)
  values (v_user.id, case when v_new then 'signup' else 'login' end, p_provider);

  return public.app_user_public(v_user);
end;
$$;

create or replace function public.create_app_session(p_token text, p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_token is null or p_token = '' or p_user_id is null then
    raise exception '세션을 만들 수 없습니다.';
  end if;

  delete from public.app_sessions where expires_at < now();

  insert into public.app_sessions (id, user_id, expires_at)
  values (p_token, p_user_id, now() + interval '30 days');

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.get_app_session(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.app_users;
begin
  if p_token is null or p_token = '' then
    return null;
  end if;

  select u.* into v_user
  from public.app_sessions s
  join public.app_users u on u.id = s.user_id
  where s.id = p_token
    and s.expires_at > now();

  if v_user.id is null then
    return null;
  end if;

  return public.app_user_public(v_user);
end;
$$;

create or replace function public.delete_app_session(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
begin
  select user_id into v_user_id from public.app_sessions where id = p_token;
  delete from public.app_sessions where id = p_token;

  if v_user_id is not null then
    insert into public.app_auth_events (user_id, event, provider)
    values (v_user_id, 'logout', null);
  end if;

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.delete_app_user(p_email text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.app_users where email = lower(trim(both from coalesce(p_email, '')));
  return jsonb_build_object('ok', true);
end;
$$;

grant execute on function public.signup_app_user(text, text, text) to anon, authenticated;
grant execute on function public.login_app_user(text, text) to anon, authenticated;
grant execute on function public.upsert_social_app_user(text, text, text, text) to anon, authenticated;
grant execute on function public.create_app_session(text, uuid) to anon, authenticated;
grant execute on function public.get_app_session(text) to anon, authenticated;
grant execute on function public.delete_app_session(text) to anon, authenticated;
grant execute on function public.delete_app_user(text) to anon, authenticated;

notify pgrst, 'reload schema';
