-- 공지사항 게시판. 회원은 조회만, 관리자(profiles.is_admin = true)만 작성·수정·삭제합니다.
-- Supabase SQL Editor에서 이 파일 전체를 실행하세요.
-- 관리자 지정 예:
--   update public.profiles set is_admin = true where lower(email) = '관리자이메일';

alter table public.profiles add column if not exists is_admin boolean default false;
update public.profiles set is_admin = false where is_admin is null;
comment on column public.profiles.is_admin is '공지사항 작성 권한';

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  pinned boolean not null default false,
  author_id uuid references auth.users(id) on delete set null,
  author_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.notices enable row level security;

revoke all on table public.notices from anon, public;
grant select on table public.notices to authenticated;
grant insert, update, delete on table public.notices to authenticated;
grant usage, select on sequence public.notices_id_seq to authenticated;

create or replace function public.is_notice_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.is_admin is true
  );
$$;

revoke all on function public.is_notice_admin() from public, anon;
grant execute on function public.is_notice_admin() to authenticated;

drop policy if exists notices_select_auth on public.notices;
drop policy if exists notices_insert_admin on public.notices;
drop policy if exists notices_update_admin on public.notices;
drop policy if exists notices_delete_admin on public.notices;

create policy notices_select_auth on public.notices
  for select to authenticated
  using (true);

create policy notices_insert_admin on public.notices
  for insert to authenticated
  with check (public.is_notice_admin());

create policy notices_update_admin on public.notices
  for update to authenticated
  using (public.is_notice_admin())
  with check (public.is_notice_admin());

create policy notices_delete_admin on public.notices
  for delete to authenticated
  using (public.is_notice_admin());

create index if not exists notices_created_at_idx on public.notices (pinned desc, created_at desc);

-- 회원이 자기 프로필의 is_admin 을 바꿀 수 없게 합니다. 관리자 지정은 SQL Editor에서만 합니다.
create or replace function public.protect_profile_is_admin()
returns trigger
language plpgsql
as $$
begin
  if current_user in ('postgres', 'supabase_admin') then
    return new;
  end if;
  if tg_op = 'INSERT' then
    new.is_admin := false;
    return new;
  end if;
  if new.is_admin is distinct from old.is_admin then
    new.is_admin := old.is_admin;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_protect_profile_is_admin on public.profiles;
create trigger trg_protect_profile_is_admin
before insert or update on public.profiles
for each row execute procedure public.protect_profile_is_admin();

notify pgrst, 'reload schema';
