-- 나의 약점 분석: 오답 영역.
-- Supabase SQL Editor에서 이 파일 전체를 실행하세요.

create table if not exists public.weakness_reports (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  subjects text not null,
  headline text,
  analysis text,
  drill_topic text,
  drill_label text,
  updated_at timestamptz not null default now()
);

create table if not exists public.weak_areas (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  subjects text not null,
  area text not null,
  attempted integer not null default 0,
  correct integer not null default 0,
  wrong integer not null default 0,
  wrong_rate integer not null default 0,
  sample_topic text,
  sort_rank integer not null default 1,
  updated_at timestamptz not null default now()
);

alter table public.weakness_reports alter column user_id drop not null;
alter table public.weak_areas alter column user_id drop not null;

create unique index if not exists weakness_reports_owner_subject_uidx
  on public.weakness_reports (
    coalesce(user_id, '00000000-0000-0000-0000-000000000000'::uuid),
    subjects
  );

create unique index if not exists weak_areas_owner_subject_area_uidx
  on public.weak_areas (
    coalesce(user_id, '00000000-0000-0000-0000-000000000000'::uuid),
    subjects,
    area
  );

alter table public.weakness_reports enable row level security;
alter table public.weak_areas enable row level security;

revoke all on table public.weakness_reports from anon, public;
revoke all on table public.weak_areas from anon, public;
grant select, insert, update, delete on table public.weakness_reports to authenticated;
grant select, insert, update, delete on table public.weak_areas to authenticated;

drop policy if exists weakness_reports_select_own on public.weakness_reports;
drop policy if exists weakness_reports_insert_own on public.weakness_reports;
drop policy if exists weakness_reports_update_own on public.weakness_reports;
drop policy if exists weakness_reports_delete_own on public.weakness_reports;
drop policy if exists weak_areas_select_own on public.weak_areas;
drop policy if exists weak_areas_insert_own on public.weak_areas;
drop policy if exists weak_areas_update_own on public.weak_areas;
drop policy if exists weak_areas_delete_own on public.weak_areas;

create policy weakness_reports_select_own on public.weakness_reports
  for select to authenticated using (auth.uid() = user_id);
create policy weakness_reports_insert_own on public.weakness_reports
  for insert to authenticated with check (auth.uid() = user_id);
create policy weakness_reports_update_own on public.weakness_reports
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy weakness_reports_delete_own on public.weakness_reports
  for delete to authenticated using (auth.uid() = user_id);
create policy weak_areas_select_own on public.weak_areas
  for select to authenticated using (auth.uid() = user_id);
create policy weak_areas_insert_own on public.weak_areas
  for insert to authenticated with check (auth.uid() = user_id);
create policy weak_areas_update_own on public.weak_areas
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy weak_areas_delete_own on public.weak_areas
  for delete to authenticated using (auth.uid() = user_id);

drop function if exists public.list_weakness();
drop function if exists public.save_weakness(jsonb);
drop function if exists public.claim_guest_weakness();

create or replace function public.list_weakness()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_out jsonb;
begin
  select coalesce(jsonb_agg(item order by ord), '[]'::jsonb)
  into v_out
  from (
    select
      r.id as ord,
      jsonb_build_object(
        'subjects', r.subjects,
        'headline', r.headline,
        'analysis', r.analysis,
        'drill_topic', r.drill_topic,
        'drill_label', r.drill_label,
        'areas', coalesce((
          select jsonb_agg(
            jsonb_build_object(
              'area', a.area,
              'attempted', a.attempted,
              'correct', a.correct,
              'wrong', a.wrong,
              'wrong_rate', a.wrong_rate,
              'sample_topic', a.sample_topic
            )
            order by a.sort_rank, a.wrong desc
          )
          from public.weak_areas a
          where a.subjects = r.subjects
            and (
              (v_uid is null and a.user_id is null)
              or a.user_id = v_uid
            )
        ), '[]'::jsonb)
      ) as item
    from public.weakness_reports r
    where (v_uid is null and r.user_id is null) or r.user_id = v_uid
  ) q;

  return v_out;
end;
$$;

create or replace function public.save_weakness(p_rows jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  rec jsonb;
  area jsonb;
  v_subjects text;
  v_rank integer;
begin
  delete from public.weak_areas
  where (v_uid is null and user_id is null) or user_id = v_uid;
  delete from public.weakness_reports
  where (v_uid is null and user_id is null) or user_id = v_uid;

  for rec in
    select value from jsonb_array_elements(coalesce(p_rows, '[]'::jsonb))
  loop
    v_subjects := nullif(trim(both from coalesce(rec->>'subjects', rec->>'subjectId', '')), '');
    if v_subjects is null then
      continue;
    end if;

    insert into public.weakness_reports (
      user_id, subjects, headline, analysis, drill_topic, drill_label, updated_at
    ) values (
      v_uid,
      v_subjects,
      nullif(trim(both from coalesce(rec->>'headline', '')), ''),
      nullif(trim(both from coalesce(rec->>'analysis', '')), ''),
      nullif(trim(both from coalesce(rec->>'drill_topic', rec->>'drillTopic', '')), ''),
      nullif(trim(both from coalesce(rec->>'drill_label', rec->>'drillLabel', '')), ''),
      now()
    );

    v_rank := 0;
    for area in
      select value from jsonb_array_elements(coalesce(rec->'areas', '[]'::jsonb))
    loop
      if nullif(trim(both from coalesce(area->>'area', area->>'name', '')), '') is null then
        continue;
      end if;
      v_rank := v_rank + 1;
      insert into public.weak_areas (
        user_id, subjects, area, attempted, correct, wrong, wrong_rate, sample_topic, sort_rank, updated_at
      ) values (
        v_uid,
        v_subjects,
        nullif(trim(both from coalesce(area->>'area', area->>'name', '')), ''),
        greatest(coalesce((area->>'attempted')::integer, 0), 0),
        greatest(coalesce((area->>'correct')::integer, 0), 0),
        greatest(coalesce((area->>'wrong')::integer, 0), 0),
        greatest(coalesce((area->>'wrong_rate')::integer, (area->>'wrongRate')::integer, 0), 0),
        nullif(trim(both from coalesce(area->>'sample_topic', area->>'sampleTopic', '')), ''),
        v_rank,
        now()
      );
    end loop;
  end loop;

  return public.list_weakness();
end;
$$;

create or replace function public.claim_guest_weakness()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_own integer := 0;
  v_guest integer := 0;
begin
  if v_uid is null then
    return 0;
  end if;

  select count(*) into v_own from public.weakness_reports where user_id = v_uid;
  select count(*) into v_guest from public.weakness_reports where user_id is null;

  if v_guest = 0 then
    return 0;
  end if;

  if v_own > 0 then
    delete from public.weak_areas where user_id is null;
    delete from public.weakness_reports where user_id is null;
    return 0;
  end if;

  update public.weak_areas set user_id = v_uid, updated_at = now() where user_id is null;
  update public.weakness_reports set user_id = v_uid, updated_at = now() where user_id is null;
  return v_guest;
end;
$$;

grant execute on function public.list_weakness() to anon, authenticated;
grant execute on function public.save_weakness(jsonb) to anon, authenticated;
grant execute on function public.claim_guest_weakness() to authenticated;

notify pgrst, 'reload schema';
