-- AI 선생님 사용횟수.
-- Supabase SQL Editor에서 이 파일 전체를 실행하세요.

create table if not exists public.ai_usage (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  used integer not null default 0,
  used_period integer not null default 0,
  period_start date,
  period_kind text not null default 'day',
  updated_at timestamptz not null default now()
);

alter table public.ai_usage add column if not exists used integer;
alter table public.ai_usage add column if not exists used_period integer;
alter table public.ai_usage add column if not exists period_start date;
alter table public.ai_usage add column if not exists period_kind text;
alter table public.ai_usage add column if not exists updated_at timestamptz;

alter table public.ai_usage alter column user_id drop not null;
alter table public.ai_usage alter column used set default 0;
alter table public.ai_usage alter column used_period set default 0;
alter table public.ai_usage alter column period_kind set default 'day';
alter table public.ai_usage alter column updated_at set default now();

create unique index if not exists ai_usage_owner_uidx
  on public.ai_usage (coalesce(user_id, '00000000-0000-0000-0000-000000000000'::uuid));

alter table public.ai_usage enable row level security;

revoke all on table public.ai_usage from anon, public;
grant select, insert, update, delete on table public.ai_usage to authenticated;

drop policy if exists ai_usage_select_own on public.ai_usage;
drop policy if exists ai_usage_insert_own on public.ai_usage;
drop policy if exists ai_usage_update_own on public.ai_usage;
drop policy if exists ai_usage_delete_own on public.ai_usage;

create policy ai_usage_select_own on public.ai_usage
  for select to authenticated using (auth.uid() = user_id);
create policy ai_usage_insert_own on public.ai_usage
  for insert to authenticated with check (auth.uid() = user_id);
create policy ai_usage_update_own on public.ai_usage
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy ai_usage_delete_own on public.ai_usage
  for delete to authenticated using (auth.uid() = user_id);

drop function if exists public.get_ai_usage();
drop function if exists public.save_ai_usage(integer, integer, date, text);
drop function if exists public.claim_guest_ai_usage();

create or replace function public.get_ai_usage()
returns setof public.ai_usage
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is not null then
    return query select * from public.ai_usage where user_id = v_uid limit 1;
  else
    return query select * from public.ai_usage where user_id is null limit 1;
  end if;
end;
$$;

create or replace function public.save_ai_usage(
  p_used integer default 0,
  p_used_period integer default 0,
  p_period_start date default null,
  p_period_kind text default 'day'
)
returns public.ai_usage
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_row public.ai_usage;
  v_kind text := case when p_period_kind in ('day', 'month') then p_period_kind else 'day' end;
begin
  select * into v_row
  from public.ai_usage
  where (v_uid is null and user_id is null) or user_id = v_uid
  limit 1;

  if v_row.id is not null then
    update public.ai_usage
    set
      used = greatest(coalesce(p_used, 0), 0),
      used_period = greatest(coalesce(p_used_period, 0), 0),
      period_start = p_period_start,
      period_kind = v_kind,
      updated_at = now()
    where id = v_row.id
    returning * into v_row;
    return v_row;
  end if;

  insert into public.ai_usage (
    user_id, used, used_period, period_start, period_kind, updated_at
  ) values (
    v_uid,
    greatest(coalesce(p_used, 0), 0),
    greatest(coalesce(p_used_period, 0), 0),
    p_period_start,
    v_kind,
    now()
  )
  returning * into v_row;

  return v_row;
end;
$$;

create or replace function public.claim_guest_ai_usage()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_guest public.ai_usage;
  v_own public.ai_usage;
begin
  if v_uid is null then
    return 0;
  end if;

  select * into v_guest from public.ai_usage where user_id is null limit 1;
  if v_guest.id is null then
    return 0;
  end if;

  select * into v_own from public.ai_usage where user_id = v_uid limit 1;
  if v_own.id is not null then
    delete from public.ai_usage where id = v_guest.id;
    return 0;
  end if;

  update public.ai_usage set user_id = v_uid, updated_at = now() where id = v_guest.id;
  return 1;
end;
$$;

grant execute on function public.get_ai_usage() to anon, authenticated;
grant execute on function public.save_ai_usage(integer, integer, date, text) to anon, authenticated;
grant execute on function public.claim_guest_ai_usage() to authenticated;

notify pgrst, 'reload schema';
