-- 오류 신고 게시판. 회원은 글쓰기·비밀번호로 본인 글 확인, 관리자(profiles.is_admin)는 열람·답변·삭제합니다.
-- 공지사항과 같은 관리자 권한(is_notice_admin)을 사용합니다.
-- Supabase SQL Editor에서 이 파일 전체를 실행하세요.

create extension if not exists pgcrypto with schema extensions;

alter table public.profiles add column if not exists is_admin boolean default false;

create or replace function public.is_notice_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.is_admin is true
  );
$$;

revoke all on function public.is_notice_admin() from public, anon;
grant execute on function public.is_notice_admin() to authenticated;

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  password_hash text not null,
  author_id uuid references auth.users(id) on delete set null,
  author_name text,
  answer text,
  answered_at timestamptz,
  answered_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.reports enable row level security;

revoke all on table public.reports from anon, public, authenticated;
grant usage, select on sequence public.reports_id_seq to authenticated;

create index if not exists reports_created_at_idx on public.reports (created_at desc);

create or replace function public.report_summary(r public.reports)
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'id', r.id,
    'title', r.title,
    'created_at', r.created_at,
    'has_answer', coalesce(nullif(btrim(coalesce(r.answer, '')), ''), null) is not null
  );
$$;

create or replace function public.report_detail(r public.reports)
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'id', r.id,
    'title', r.title,
    'content', r.content,
    'author_name', r.author_name,
    'created_at', r.created_at,
    'updated_at', r.updated_at,
    'answer', r.answer,
    'answered_at', r.answered_at,
    'has_answer', coalesce(nullif(btrim(coalesce(r.answer, '')), ''), null) is not null
  );
$$;

create or replace function public.list_reports()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  payload jsonb;
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;
  select coalesce(jsonb_agg(public.report_summary(r) order by r.created_at desc), '[]'::jsonb)
    into payload
  from public.reports r;
  return payload;
end;
$$;

create or replace function public.create_report(p_title text, p_content text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  title_text text := btrim(coalesce(p_title, ''));
  body_text text := btrim(coalesce(p_content, ''));
  pass_text text := coalesce(p_password, '');
  author text;
  rec public.reports;
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;
  if title_text = '' or body_text = '' then
    raise exception '제목과 내용을 입력해 주세요.';
  end if;
  if char_length(pass_text) < 4 then
    raise exception '비밀번호는 4자 이상이어야 합니다.';
  end if;
  select coalesce(nullif(btrim(p.nickname), ''), '회원')
    into author
  from public.profiles p
  where p.id = auth.uid();
  author := coalesce(author, '회원');
  insert into public.reports (title, content, password_hash, author_id, author_name)
  values (title_text, body_text, crypt(pass_text, gen_salt('bf')), auth.uid(), author)
  returning * into rec;
  return public.report_detail(rec);
end;
$$;

create or replace function public.open_report(p_id bigint, p_password text default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, extensions
as $$
declare
  rec public.reports;
  pass_text text := coalesce(p_password, '');
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;
  select * into rec from public.reports where id = p_id;
  if not found then
    raise exception '글을 찾을 수 없습니다.';
  end if;
  if public.is_notice_admin() then
    return public.report_detail(rec);
  end if;
  if pass_text = '' then
    raise exception '비밀번호를 입력해 주세요.';
  end if;
  if rec.password_hash is distinct from crypt(pass_text, rec.password_hash) then
    raise exception '비밀번호가 올바르지 않습니다.';
  end if;
  return public.report_detail(rec);
end;
$$;

create or replace function public.reply_report(p_id bigint, p_answer text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  rec public.reports;
  answer_text text := btrim(coalesce(p_answer, ''));
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;
  if not public.is_notice_admin() then
    raise exception '관리자만 답변할 수 있습니다.';
  end if;
  if answer_text = '' then
    raise exception '답변을 입력해 주세요.';
  end if;
  update public.reports
     set answer = answer_text,
         answered_at = now(),
         answered_by = auth.uid(),
         updated_at = now()
   where id = p_id
  returning * into rec;
  if not found then
    raise exception '글을 찾을 수 없습니다.';
  end if;
  return public.report_detail(rec);
end;
$$;

create or replace function public.delete_report(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;
  if not public.is_notice_admin() then
    raise exception '관리자만 삭제할 수 있습니다.';
  end if;
  delete from public.reports where id = p_id;
  if not found then
    raise exception '글을 찾을 수 없습니다.';
  end if;
  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.report_summary(public.reports) from public, anon;
revoke all on function public.report_detail(public.reports) from public, anon;
revoke all on function public.list_reports() from public, anon;
revoke all on function public.create_report(text, text, text) from public, anon;
revoke all on function public.open_report(bigint, text) from public, anon;
revoke all on function public.reply_report(bigint, text) from public, anon;
revoke all on function public.delete_report(bigint) from public, anon;

grant execute on function public.list_reports() to authenticated;
grant execute on function public.create_report(text, text, text) to authenticated;
grant execute on function public.open_report(bigint, text) to authenticated;
grant execute on function public.reply_report(bigint, text) to authenticated;
grant execute on function public.delete_report(bigint) to authenticated;

notify pgrst, 'reload schema';
