-- 학생 문제 풀이 기록. user_id 는 Supabase Auth(auth.users)를 참조합니다.
-- Supabase SQL Editor에서 supabase-auth-users.sql 을 먼저 실행하세요.

create table if not exists public.user_answers (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  question_id bigint references public.questions(id) on delete cascade,
  selected_answer integer,
  is_correct boolean,
  response_time integer,
  answered_at timestamptz default now()
);

create index if not exists user_answers_user_id_idx
  on public.user_answers (user_id, answered_at desc);

create index if not exists user_answers_question_id_idx
  on public.user_answers (question_id);

alter table public.user_answers enable row level security;

revoke all on table public.user_answers from anon, public;
grant select, insert, delete on table public.user_answers to authenticated;

drop policy if exists user_answers_select_own on public.user_answers;
drop policy if exists user_answers_insert_own on public.user_answers;
drop policy if exists user_answers_delete_own on public.user_answers;

create policy user_answers_select_own on public.user_answers
  for select to authenticated using (auth.uid() = user_id);
create policy user_answers_insert_own on public.user_answers
  for insert to authenticated with check (auth.uid() = user_id);
create policy user_answers_delete_own on public.user_answers
  for delete to authenticated using (auth.uid() = user_id);

notify pgrst, 'reload schema';
