-- 문제 테이블은 반드시 public 스키마에 둡니다.
create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  subjects text not null,
  kind text not null,
  type text not null,
  question text not null,
  option1 text not null,
  option2 text not null,
  option3 text not null,
  option4 text not null,
  answer integer not null check (answer between 1 and 4),
  explanation text not null,
  created_at timestamptz default now()
);

insert into public.questions (
  subjects, kind, type, question,
  option1, option2, option3, option4,
  answer, explanation
)
select
  'korean',
  '기출문제',
  '문법 · 띄어쓰기',
  '다음 중 띄어쓰기가 옳은 것은?',
  '할수있다',
  '할수 있다',
  '할 수있다',
  '할 수 있다',
  4,
  '''수''는 의존 명사이므로 앞말과 띄어 쓰고, ''있다''도 별개의 용언이므로 띄어 씁니다. 따라서 ''할 수 있다''가 옳습니다.'
where not exists (
  select 1 from public.questions where subjects = 'korean' and question = '다음 중 띄어쓰기가 옳은 것은?'
);

alter table public.questions enable row level security;

drop policy if exists "questions_public_read" on public.questions;
create policy "questions_public_read"
  on public.questions
  for select
  to anon, authenticated
  using (true);

grant usage on schema public to anon, authenticated;
grant select on table public.questions to anon, authenticated;

notify pgrst, 'reload schema';
